syntax = "proto3";
package protos;

message Empty {}
service ValidatorService {
    // Sync: Get more than one block for resyncing fully.
    rpc GetHistory(GetHistoryQuery) returns (GetHistoryResponse);
    // Sync: Get the latest block for reconnecting to network.
    rpc GetLatest(GetLatestQuery) returns (GetLatestResponse);

    // Connect to another node.
    rpc Hello(HelloMessage) returns (Empty);

    // Gossip transactions to other nodes.
    rpc GossipTxs(stream TxGossip) returns (stream TxGossip);

    // Consensus: Propose.
    rpc Propose(ProposeMessage) returns (Empty);
    // Consensus: Prevote.
    rpc Prevote(VoteMessage) returns (Empty);
    // Consensus: Precommit.
    rpc Precommit(VoteMessage) returns (Empty);
}

// HANDSHAKE.
message HelloMessage {}

// 
// SYNC.
// 

message GetHistoryQuery {
    int64 start_height = 1;
    int64 end_height = 2;
}

message GetHistoryResponse {
    repeated Block blocks = 1;
    repeated VoteMessage votes = 2;
}

message GetLatestQuery {}

message GetLatestResponse {
    repeated VoteMessage votes = 1;
    int64 localTime = 2;
}

message Block {
    repeated Transaction txs = 1;
    bytes proposer = 2;
    bytes previous_block_hash = 3;
    int64 height = 4;
}

message TxGossip {
    repeated Transaction txs = 1;
}

message Transaction {
    bytes data = 1;
    bytes sig = 2;
    bytes sender = 3;
    int64 timestamp = 4;
}

enum MessageType {
    PROPOSE = 0;
    PREVOTE = 1;
    PRECOMMIT = 2;
}

message ProposeMessage {
    MessageType msgType = 1; // set as PROPOSE
    int64 round = 2;
    int64 height = 3;
    Block value = 4;
    bytes sig = 5;
    bytes sender = 6;
    int64 timestamp = 7;
}

message VoteMessage {
    MessageType msgType = 1; // set as PREVOTE or PRECOMMIT
    int64 round = 2;
    int64 height = 3;
    bytes value = 4;
    bytes sig = 5;
    bytes sender = 6;
    int64 timestamp = 7;
}
